services:
  boulderdb-nextjs:
    build:
      context: .
      dockerfile: nextjs/Dockerfile

  boulderdb-nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    expose:
      - 80
    environment:
      VIRTUAL_HOST: $PROJECT_HOSTNAME
      LETSENCRYPT_HOST: $PROJECT_HOSTNAME
      LETSENCRYPT_EMAIL: infra@atelierdisko.de
    depends_on:
      dpa-com-nextjs:
        condition: service_started

networks:
  default:
    external:
      name: nginx-proxy
